#!/bin/bash
#
####  Where this script and config files live
WGDIR=/etc/wireguard

#######################################
# Programmatically assigned, no touchie

PROG="${0##*/}"
CONFIG=${PROG//wg-/}
SERVER=${CONFIG//\.*/}
CONFIG=${WGDIR}/${SERVER}.conf
HN=$(hostname)

SK=$(cat ${WGDIR}/servers/${SERVER}.publickey 2>/dev/null)
HK=$(cat ${WGDIR}/private/${HN}.publickey 2>/dev/null)
PK=$(cat ${WGDIR}/private/${HN}.privatekey 2>/dev/null)

check_keys() {
        if [ -z "${SK}" ]
        then
        	echo "Can't continue - server publickey is missing!"
        	exit 1
        elif [ -z "$(grep ${SK} ${CONFIG})" ];
        then
                sed -i "s|PublicKey.*|PublicKey = ${SK}|g" ${CONFIG}
        fi
        if [ -z "${PK}" ]
        then
        	echo "Can't continue - client privatekey is missing!"
        	exit 1
        elif [ -z "$(grep ${PK} ${CONFIG})" ];
        then
		sed -i "s|PrivateKey.*|PrivateKey = ${PK}|g" ${CONFIG}
	fi
	if [ -z "${HK}" ]
	then
		echo "Can't continue - client publickey is missing!"
		exit 1
	fi
}

stop() {
	iptables -D INPUT -p udp -m udp --dport ${CPORT} -j ACCEPT

	wg-quick down ${SERVER}
	rmmod wireguard
}

start() {

	check_keys

	DEV=$(awk 'BEGIN { IGNORECASE=1 } /^[a-z0-9]+[ \t]+00000000/ { print $1 }' /proc/net/route)
	DGW=$(ip route show dev ${DEV} | grep default | awk '{print $3}')
	PEER=$(grep '^Endpoint' ${CONFIG} | sed 's/.*= \(.*\):.*/\1/g;')
	sed -i "s/\(ip -4 route add\) \(.*\) via .*/\1 ${PEER} via ${DGW}/g" ${CONFIG}
	sed -i "s/\(ip -4 route del\) \(.*\) via .*/\1 ${PEER} via ${DGW}/g" ${CONFIG}
	sed -i "s/default dev.*/default dev ${SERVER}/g" ${CONFIG}
	sed -i "s/default via.*/default via ${DGW}/g" ${CONFIG}

	wg-quick up ${SERVER}

	WANv6=$(grep 'ip -6 addr add' ${CONFIG} | sed 's/.*ip -6 addr add //g; s/dev sixbroker//g;')
	if [ -n "${WANv6}" ];
	then
		ip route add ::/0 via ${WANv6//::*/::1} dev ${SERVER}
	fi

	iptables -I INPUT -p udp -m udp --dport ${CPORT} -j ACCEPT

}

status() {
	if [ -z "$( wg show interfaces )" ];
	then
		echo "Not running"
	else
	        wg show ${SERVER}
                ip -4 route show dev ${SERVER}
                ip -6 route show dev ${SERVER}
	fi
}

CPORT=$(grep -i 'ListenPort' ${CONFIG} | cut -f 2 -d=)

case ${1} in
	start) check_keys; start
		;;
	stop) stop
		;;
	keys) check_keys;
		grep Key ${CONFIG}
		;;
	status) check_keys; status
		;;
	*) echo "$0 start|stop|status"
		;;
esac
